name: cloudflare_turnstile
description: The Cloudflare Turnstile Widget is an unofficial Flutter package designed to seamlessly integrate Cloudflare's Turnstile functionality into your Flutter applications.
repository: https://github.com/Nika0000/cloudflare_turnstile
version: 0.0.1+1

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_android: ^1.0.13
  flutter_inappwebview_ios: ^1.0.13
  flutter_inappwebview_platform_interface: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - hcaptcha
  - recaptcha
  - cloudflare-turnstile