name: cloudflare_turnstile
description: A free CAPTCHAs alternative to enhance security and protect against bots.
repository: https://github.com/Nika0000/cloudflare_turnstile/tree/feature/webview_flutter
version: 1.2.3

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

topics:
  - hcaptcha
  - recaptcha
  - cloudflare-turnstile